on: [push, workflow_dispatch]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Run groovy library method
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          repository: matdavy1/groovy-library
          path: ./groovy-library
      - name: setup groovy
        run: sudo apt-get install groovy
      - name: run hello action
        run: groovy ./groovy-library/hello mat